### PR TITLE
Fix white screen on session form reload

### LINKED ISSUE #288: session form reload turns into a white screen

### PR DESCRIPTION
**Pull request by sjenzh**
# Overview
Fixes reload issue on session form, when session form is reloaded, a white screen used to be shown. Even when clicking return, the page is white; the session overview is no longer visible
fixes #288 

## Changes
Adds Errorboundary for when loading the Session Form page does not succeed, as well as adding a loading screen to the page until a connection is established

## How to test?
Open session form and click refresh to check if fix works

### CODE REVIEW

File: frontend/src/components/organisms/LoadingScreen/LoadingScreen.jsx [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+        }
+      />
+    ) : (
+      <LoadingIndicator
+        loading={true}
+        text={
+          <>
+            <h1>Loading...</h1>
+            <h1>
+              Please refresh the tab. If the delay continues, hang tight—your connection may be
```
Comment (NCEghtebas) [inline frontend/src/components/organisms/LoadingScreen/LoadingScreen.jsx]: "if the delay continues after refreshing,"

**Review by NCEghtebas — APPROVED** [review]
great!

**Review by NCEghtebas — APPROVED** [review]
